import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { SessionProvider } from "next-auth/react";
import { Provider } from 'react-redux';
import { store } from '@/store';
import { SonnerToaster } from '@/components/ui/sonner-toaster';
import { Analytics } from "@vercel/analytics/react";
import { TailwindIndicator } from "@/components/tailwind-indicator";
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider>
          <Provider store={store}>{children}</Provider>
        </SessionProvider>
        <SonnerToaster/>
         <Analytics />
         <TailwindIndicator />
      </body>
    </html>
  )
}
